[pytest]
DJANGO_SETTINGS_MODULE = dentalsozluk.settings
python_files = tests.py test_*.py *_tests.py
python_classes = Test*
python_functions = test_*
addopts =
    --strict-markers
    --reuse-db
    --nomigrations
    --cov=terms
    --cov=dentalsozluk
    --cov-report=html
    --cov-report=term-missing:skip-covered
    --no-cov-on-fail
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    integration: marks tests as integration tests
    unit: marks tests as unit tests
