# Generated by Django 5.2.3 on 2025-06-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DentalTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('english_equivalent', models.CharField(blank=True, max_length=100, null=True)),
                ('latin_equivalent', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
