# Generated by Django 5.2.3 on 2025-06-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentalterm',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
