# Generated by Django 5.2.4 on 2025-07-18 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0002_dentalterm_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='(Opsiyonel) Hata hakkında ekstra bilgi')),
                ('honeypot', models.CharField(blank=True, help_text='Bot kontrolü için gizli alan', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_reports', to='terms.dentalterm')),
            ],
        ),
    ]
