# Generated by Django 5.2.4 on 2025-07-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0003_errorreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorreport',
            name='session_key',
            field=models.CharField(blank=True, help_text='Kullanıcı oturumu için', max_length=40, null=True),
        ),
    ]
