# Generated by Django 5.2.4 on 2025-08-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0004_errorreport_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentalterm',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
