# Generated by Django 5.2.4 on 2025-08-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0005_alter_dentalterm_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentalterm',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
