# Generated by Django 5.2.4 on 2026-02-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0006_alter_dentalterm_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentalterm',
            name='search_aliases',
            field=models.TextField(blank=True, help_text='Alternatif yazılışlar (virgülle ayırın). Örn: miyokart, myokard', null=True),
        ),
    ]
